SOURCES += payload/ble_freertos.c
SOURCES += payload/rtos.c
SOURCES += payload/radio_task.c
SOURCES += payload/config_task.c

SOURCES += payload/ble_config.cpp
SOURCES += payload/ble_phy.cpp
SOURCES += payload/ble_usr.cpp
SOURCES += payload/ble_device_init.cpp
SOURCES += payload/ble_server.cpp
SOURCES += payload/ble_app_protocol.cpp
SOURCES += payload/aes_cbc.cpp
SOURCES += payload/sha256.c

include payload/micro-aes/Makefile.include
include payload/micro-ecc/Makefile.include
